import { Metadata } from "next"
import { Heading, Text } from "@medusajs/ui"

export const metadata: Metadata = {
  title: "Terms of Use",
}

export default function TermsOfUsePage() {
  return (
    <div className="py-12">
      <div className="content-container">
        <div className="max-w-3xl mx-auto glass p-10 rounded-2xl border border-white/10">
          <Heading level="h1" className="text-3xl text-white mb-8">Terms of Use 📜</Heading>
          
          <div className="flex flex-col gap-y-6 text-gray-300 leading-relaxed">
            <Text>
              Welcome to KandiLand. By accessing or using our website, you agree to be bound by these Terms of Use.
            </Text>

            <Heading level="h2" className="text-xl text-white mt-4">1. AI Generation</Heading>
            <Text>
              Designs generated by our AI are unique to the best of our knowledge. You own the NFT representing the design once purchased.
            </Text>

            <Heading level="h2" className="text-xl text-white mt-4">2. Purchases</Heading>
            <Text>
              You agree to provide current, complete, and accurate purchase and account information for all purchases made at our store.
            </Text>

            <Heading level="h2" className="text-xl text-white mt-4">3. Prohibited Uses</Heading>
            <Text>
              You may not use our products for any illegal or unauthorized purpose nor may you, in the use of the Service, violate any laws in your jurisdiction.
            </Text>
          </div>
        </div>
      </div>
    </div>
  )
}