import { Metadata } from "next"
import { Heading, Text } from "@medusajs/ui"
import LocalizedClientLink from "@modules/common/components/localized-client-link"

export const metadata: Metadata = {
  title: "Customer Service",
  description: "We are here to help.",
}

export default function CustomerServicePage() {
  return (
    <div className="py-12 min-h-[70vh] bg-ui-bg-subtle transition-colors duration-300">
      <div className="content-container flex justify-center">
        <div className="max-w-2xl w-full bg-ui-bg-base p-8 small:p-10 rounded-2xl border border-ui-border-base shadow-sm">
          
          <Heading level="h1" className="text-3xl text-ui-fg-base mb-6">
            Customer Service 🤝
          </Heading>
          
          <div className="flex flex-col gap-y-6 text-ui-fg-subtle">
            <section>
              <Heading level="h2" className="text-xl text-ui-fg-base mb-2">
                Contact Us
              </Heading>
              <Text>
                Have a question about your Kandi? Need help with an order? 
                Visit our{" "}
                <LocalizedClientLink 
                  href="/contact" 
                  className="text-pink-500 hover:text-pink-600 dark:hover:text-pink-400 transition-colors font-medium underline"
                >
                  Contact Page
                </LocalizedClientLink>
                {" "}to get in touch with the Kandi Creations team.
              </Text>
            </section>

            <div className="h-px w-full bg-ui-border-base my-2" />

            <section>
              <Heading level="h2" className="text-xl text-ui-fg-base mb-2">
                Shipping & Delivery
              </Heading>
              <Text>
                All Kandi Creations pieces are custom-made to order. Please allow 
                <strong className="text-ui-fg-base"> 3-5 business days</strong> for assembly before shipping. You will receive a tracking number via email once your order ships.
              </Text>
            </section>

            <div className="h-px w-full bg-ui-border-base my-2" />

            <section>
              <Heading level="h2" className="text-xl text-ui-fg-base mb-2">
                Returns & Exchanges
              </Heading>
              <Text>
                Because every piece is custom generated by AI and hand-assembled for you, 
                <strong className="text-ui-fg-base"> all sales are final</strong>. However, if your item arrives damaged, please contact us within 48 hours of delivery.
              </Text>
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}