import { Metadata } from "next"
import { Heading, Text, Container } from "@medusajs/ui"

export const metadata: Metadata = {
  title: "Customer Service",
  description: "We are here to help.",
}

export default function CustomerServicePage() {
  return (
    <div className="py-12 min-h-[70vh]">
      <div className="content-container flex justify-center">
        <div className="max-w-2xl w-full glass p-10 rounded-2xl border border-white/10">
          <Heading level="h1" className="text-3xl text-white mb-6">Customer Service 🤝</Heading>
          
          <div className="flex flex-col gap-y-6 text-gray-300">
            <section>
              <Heading level="h2" className="text-xl text-white mb-2">Contact Us</Heading>
              <Text>
                Have a question about your Kandi? Need help with an order? 
                Reach out to us at <a href="mailto:support@kandiland.xyz" className="text-pink-400 hover:text-pink-300 transition-colors">support@kandiland.xyz</a>.
              </Text>
            </section>

            <div className="h-px w-full bg-white/10 my-2" />

            <section>
              <Heading level="h2" className="text-xl text-white mb-2">Shipping & Delivery</Heading>
              <Text>
                All Phygital Kandi bracelets are custom-made to order. Please allow 
                <strong> 3-5 business days</strong> for assembly before shipping. You will receive a tracking number via email once your order ships.
              </Text>
            </section>

            <div className="h-px w-full bg-white/10 my-2" />

            <section>
              <Heading level="h2" className="text-xl text-white mb-2">Returns & Exchanges</Heading>
              <Text>
                Because every piece is custom generated by AI and hand-assembled for you, 
                <strong> all sales are final</strong>. However, if your item arrives damaged, please contact us within 48 hours of delivery.
              </Text>
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}